[theme]
primaryColor = "#10B981"        # Vibrant green for buttons and accents
backgroundColor = "#F3F4F6"     # Light gray for contrast
secondaryBackgroundColor = "#FFFFFF"  # White for cards
textColor = "#1F2937"           # Dark gray for readability
font = "sans serif"
base = "light"